name: Makefile CI

on:
  push:
    branches: [ "rtl8189fs" ]
  pull_request:
    branches: [ "rtl8189fs" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: kernel
      run: |
        DEB=https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.9.300/amd64/linux-headers-4.9.300-0409300_4.9.300-0409300.202202082136_all.deb
        wget -nv $DEB
        sudo dpkg --force-all -i *.deb
        echo "KVER=$(echo $DEB | cut -d '_' -f 2 | rev | cut -c14- | rev)-generic" >> $GITHUB_ENV
        
    - uses: actions/checkout@v3
    
    - name: build
      run: make ARCH=arm KVER=$KVER CONFIG_PLATFORM_I386_PC=y
      

