name: Makefile CI

on:
  push:
    branches: [ "rtl8189fs" ]
  pull_request:
    branches: [ "rtl8189fs" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: kernel
      run: |
        wget -nv https://kernel.ubuntu.com/~kernel-ppa/mainline/v4.9.300/armhf/linux-headers-4.9.300-0409300-generic_4.9.300-0409300.202202082136_armhf.deb
        sudo dpkg --force-all -i *.deb
        echo "KVER=$(echo $ALL_DEB | cut -d '_' -f 2 | rev | cut -c14- | rev)-generic" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: build
      run: make KVER=$KVER CONFIG_PLATFORM_HISILICON=y
